language: java
jdk:
  - oraclejdk11
before_install:
  - cd 18_DeployInAWS/
services:
  - docker
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
notifications:
  email: false
