language: 
  - python
  - java
python:
  - "3.6"  
jdk:
  - oraclejdk11
before_install:
  # Build Maven Project
  - sudo apt-get update  
  - cd 18_DeployInAWS/RestWithSpringBootUdemy/
  - echo "Let's start Maven Package!"
  - mvn clean package
  - cd ..
services:
  - docker
# install:
  # - pip install --user pysay
  # - export PATH=$PATH:~/.local/bin/
script:
  - docker-compose build
before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin  
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
notifications:
  email: false
