services: docker
language: java
jdk:
  - oraclejdk11
before_install:
  - cd 16\ Docker/
  - echo "We are in the Docker folder."
  - echo '$DOCKER_PASSWORD' | docker login -u '$DOCKER_USERNAME' --password-stdin
install: true
script:
  - docker-compose build 
after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker tag firstimage leandrocgsi/udemy-mysql-spring;
      docker push leandrocgsi/udemy-mysql-spring;
    fi
notifications:
  email: false
