language: java
sudo: required
jdk:
  - oraclejdk8
notifications:
  - emails: false
script:
 - cd 06_Migrations 
 - echo "Entered 06_Migrations."
 - mvn clean
 - sudo rm -rf target
after_success:
  - bash <(curl -s https://codecov.io/bash)
