language: java
sudo: required
jdk:
  - oraclejdk8
notifications:
  - emails: false
script:
 - cd 02_FirstEndpoints 
 - echo "Entered 02_FirstEndpoints."
 - mvn clean
 - sudo rm -rf target
after_success:
  - bash <(curl -s https://codecov.io/bash)
