language: bash
services: docker
before_install:
  - cd 17\ CIWithAWS/
  - echo "OK! Here we go!"
script:
  - docker-compose build 
before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
deploy:
  provider: script
  script:
    docker push leandrocgsi/mysql-rest-with-spring-boot-udemy;
    docker push leandrocgsi/rest-with-spring-boot-udemy;
  on:
    branch: master
after_success:
  - pip install --user awscli
  - export PATH=$PATH:/$HOME/.local/bin
  - eval $(aws ecr get-login --no-include-email --region us-east-2)
  - docker tag leandrocgsi/rest-with-spring-boot-udemy:latest $AWS_REPO/rest-with-spring-boot-udemy:latest
  - docker push $AWS_REPO/rest-with-spring-boot-udemy:latest
notifications:
  email: false