sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk11
python:
  - "3.6"  
jdk:
  - oraclejdk11
services: docker
# addons:
#   apt:
#     packages:
#       - oraclejdk11
before_install:
  - sudo apt-get -y install python3-pip python-dev
  - sudo pip3 install -U setuptools
  - sudo pip3 install -U virtualenvwrapper
  - python3 -V
  - pip3 -V
  # Build Maven Project
  - sudo apt-get update  
  - cd 18_DeployInAWS/RestWithSpringBootUdemy/
  - echo "Let's start Maven Package!"
  - mvn clean package
  - cd ..
#install:
#  - sudo pip3 install -r requirements.txt  
services:
  - docker
# install:
  # - pip install --user pysay
  # - export PATH=$PATH:~/.local/bin/
script:
  - docker-compose build
before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin  
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
notifications:
  email: false
