language: bash
services: docker
before_install:
  - cd 16\ Docker/
  - echo "We are in the Docker folder."
script:
  - docker-compose build 
after_success:
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
  - docker push leandrocgsi/mysql-spring-boot-playground
  - docker push leandrocgsi/spring-boot-playground
notifications:
  email: false
