sudo: required
dist: bionic
language: java
jdk:
  - oraclejdk11
python:
  - "3.6"  
jdk:
  - oraclejdk11
services: docker
before_install:
  - bash run_maven_package.sh
  - cd 18_DeployInAWS/
services:
  - docker
script:
  - docker-compose build
before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin  
deploy:
  provider: script
  script:
    docker push leandrocgsi/rest-with-spring-boot-udemy;
    bash install_awscli.sh;
    bash deploy.sh;
  on:
    branch: master
notifications:
  email: false
