language: java

services: docker
before_install:
  - cd 17\ CIWithAWS/SpringBootPlayground/
  - echo "I'll Be Back!"
  - mvn clean install
  - cd ..
  - echo "OK! Here we go!"
script:
  - docker-compose build 
before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
deploy:
  provider: script
  script:
    docker push leandrocgsi/mysql-spring-boot-playground;
    docker push leandrocgsi/spring-boot-playground;
  on:
    branch: master
after_success:
  - pip install --user awscli
  - export PATH=$PATH:/$HOME/.local/bin
  - eval $(aws ecr get-login --no-include-email --region us-east-2)
  - docker tag leandrocgsi/spring-boot-playground:latest $AWS_REPO/rest-with-spring-boot-udemy:latest
  - echo "Deploy to AWS are Started!"
  - docker push $AWS_REPO/rest-with-spring-boot-udemy:latest
  # update an AWS ECS service with the new image
  # - ecs-deploy -c $CLUSTER_NAME -n $SERVICE_NAME -i $AWS_REPO/rest-with-spring-boot-udemy:latest
notifications:
  email: false
