language: java
sudo: required
jdk:
  - oraclejdk8
notifications:
  - emails: false
script:
 - cd 02_FirstEndpoints 
 - echo "Entered 02_FirstEndpoints."
 - cd $(dirname $0)
 - set -e
 - sudo rm -rf build
 - mvn clean
 - sudo rm -rf target
