services: docker
language: java
jdk:
  - oraclejdk11
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - cd 16\ Docker/
  - echo "We are in the Docker folder."
install: true
script:
  - docker-compose build
deploy:
  provider: script
  script:
    # push to dockerhub
    docker push leandrocgsi/udemy-mysql-spring;
  branch: master   
