services: docker
language: java
jdk:
  - oraclejdk11
before_install:
  - cd 16\ Docker/
  - echo "We are in the Docker folder."
install: true
script:
  - docker-compose build 
after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
      docker push leandrocgsi/udemy-mysql-spring;
    fi
notifications:
  email: false
