sudo: required
language: java
jdk:
  - oraclejdk11
services:
  - docker
env:
  COMPOSE_VERSION: 3.4  
before_install:
  - cd 16\ Docker/
  - echo "We are in the Docker folder."
install: true
script:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - docker-compose build 
deploy:
  provider: script
  script:
    docker push leandrocgsi/udemy-mysql-spring;
  on:
    branch: master
notifications:
  email: false
