services: docker
language: java
jdk:
  - oraclejdk11
before_install:
  - cd 16\ Docker/
  - echo "We are in the Docker folder."
install: true
script:
  - docker-compose build 
after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker login docker.io -p '$DOCKER_PASSWORD' -u '$DOCKER_USERNAME';
      docker tag firstimage leandrocgsi/udemy-mysql-spring;
      docker push leandrocgsi/udemy-mysql-spring;
    fi
notifications:
  email: false
